# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Damons add-on
version: "0.1.0"
slug: https://github.com/darsys/hassio-addons.git
description: https://github.com/darsys/hassio-addons.git add-on
url: "https://github.com/darsys/hassio-addons/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
